[12.31.2023 11:54:53 | INFO]: Running on http://0.0.0.0:8005 (CTRL + C to quit)
[12.31.2023 11:54:55 | INFO]: Thumb_Up
[12.31.2023 11:54:56 | INFO]: Open_Palm
[12.31.2023 11:54:57 | INFO]: Thumb_Up
[12.31.2023 11:54:59 | INFO]: Closed_Fist
[12.31.2023 11:55:00 | INFO]: Open_Palm
[12.31.2023 11:55:06 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:06 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:06 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:06 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:06 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:06 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:07 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:08 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:08 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:08 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:08 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:08 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:08 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:08 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:08 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:08 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:08 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:09 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:09 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:09 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:09 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:09 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:09 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:09 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:09 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:09 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:09 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:10 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:10 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:10 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:10 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:10 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:10 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:10 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:10 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:10 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:10 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:11 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:12 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:12 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:12 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:12 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:12 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:12 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:12 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:12 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:12 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:12 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:14 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:14 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:14 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:14 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:14 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:14 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:14 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:14 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:14 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:14 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:15 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:16 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:16 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:16 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:16 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:16 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:16 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:16 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:16 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:16 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:16 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:17 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:17 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:17 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:17 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:17 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:17 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:17 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:17 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:17 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:17 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:18 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:18 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:18 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:18 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:18 | ERROR]: No connection to Patrik server
[12.31.2023 11:55:18 | ERROR]: No connection to Patrik server
[12.31.2023 11:57:11 | INFO]: Running on http://0.0.0.0:8005 (CTRL + C to quit)
[12.31.2023 11:57:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:57:23 | ERROR]: No connection to Patrik server
[12.31.2023 11:57:33 | ERROR]: No connection to Patrik server
[12.31.2023 11:57:43 | ERROR]: No connection to Patrik server
[12.31.2023 11:57:53 | ERROR]: No connection to Patrik server
[12.31.2023 11:58:03 | ERROR]: No connection to Patrik server
[12.31.2023 11:58:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:58:23 | ERROR]: No connection to Patrik server
[12.31.2023 11:58:33 | ERROR]: No connection to Patrik server
[12.31.2023 11:58:43 | ERROR]: No connection to Patrik server
[12.31.2023 11:58:53 | ERROR]: No connection to Patrik server
[12.31.2023 11:59:03 | ERROR]: No connection to Patrik server
[12.31.2023 11:59:13 | ERROR]: No connection to Patrik server
[12.31.2023 11:59:23 | ERROR]: No connection to Patrik server
[12.31.2023 11:59:33 | ERROR]: No connection to Patrik server
[12.31.2023 11:59:43 | ERROR]: No connection to Patrik server
[12.31.2023 11:59:53 | ERROR]: No connection to Patrik server
[12.31.2023 12:00:03 | ERROR]: No connection to Patrik server
[12.31.2023 12:00:13 | ERROR]: No connection to Patrik server
[12.31.2023 12:00:23 | ERROR]: No connection to Patrik server
[12.31.2023 12:00:33 | ERROR]: No connection to Patrik server
[12.31.2023 12:00:43 | ERROR]: No connection to Patrik server
[12.31.2023 12:00:53 | ERROR]: No connection to Patrik server
[12.31.2023 12:01:03 | ERROR]: No connection to Patrik server
[12.31.2023 12:01:13 | ERROR]: No connection to Patrik server
[12.31.2023 12:01:23 | ERROR]: No connection to Patrik server
[12.31.2023 12:01:33 | ERROR]: No connection to Patrik server
[12.31.2023 12:01:43 | ERROR]: No connection to Patrik server
[12.31.2023 12:01:53 | ERROR]: No connection to Patrik server
[12.31.2023 12:02:03 | ERROR]: No connection to Patrik server
[12.31.2023 12:02:13 | ERROR]: No connection to Patrik server
[12.31.2023 12:02:23 | ERROR]: No connection to Patrik server
[12.31.2023 12:02:33 | ERROR]: No connection to Patrik server
[12.31.2023 12:02:43 | ERROR]: No connection to Patrik server
[12.31.2023 12:02:53 | ERROR]: No connection to Patrik server
[12.31.2023 12:03:03 | ERROR]: No connection to Patrik server
[12.31.2023 12:03:13 | ERROR]: No connection to Patrik server
[12.31.2023 12:03:23 | ERROR]: No connection to Patrik server
[12.31.2023 12:03:33 | ERROR]: No connection to Patrik server
[12.31.2023 12:03:43 | ERROR]: No connection to Patrik server
[12.31.2023 12:03:53 | ERROR]: No connection to Patrik server
[12.31.2023 12:04:03 | ERROR]: No connection to Patrik server
[12.31.2023 12:04:13 | ERROR]: No connection to Patrik server
[12.31.2023 12:04:23 | ERROR]: No connection to Patrik server
[12.31.2023 12:04:34 | ERROR]: No connection to Patrik server
[12.31.2023 12:04:44 | ERROR]: No connection to Patrik server
[12.31.2023 12:04:54 | ERROR]: No connection to Patrik server
[12.31.2023 12:05:04 | ERROR]: No connection to Patrik server
[12.31.2023 12:05:14 | ERROR]: No connection to Patrik server
[12.31.2023 12:05:24 | ERROR]: No connection to Patrik server
[12.31.2023 12:05:34 | ERROR]: No connection to Patrik server
[12.31.2023 12:05:44 | ERROR]: No connection to Patrik server
[12.31.2023 12:05:54 | ERROR]: No connection to Patrik server
[12.31.2023 12:06:04 | ERROR]: No connection to Patrik server
[12.31.2023 12:06:14 | ERROR]: No connection to Patrik server
[12.31.2023 12:06:24 | ERROR]: No connection to Patrik server
[12.31.2023 12:06:34 | ERROR]: No connection to Patrik server
[12.31.2023 12:06:44 | ERROR]: No connection to Patrik server
[12.31.2023 12:06:54 | ERROR]: No connection to Patrik server
[12.31.2023 12:07:04 | ERROR]: No connection to Patrik server
[12.31.2023 12:07:14 | ERROR]: No connection to Patrik server
[12.31.2023 12:07:24 | ERROR]: No connection to Patrik server
[12.31.2023 12:07:34 | ERROR]: No connection to Patrik server
[12.31.2023 12:07:44 | ERROR]: No connection to Patrik server
[12.31.2023 12:07:54 | ERROR]: No connection to Patrik server
[12.31.2023 12:08:04 | ERROR]: No connection to Patrik server
[12.31.2023 12:08:14 | ERROR]: No connection to Patrik server
[12.31.2023 12:08:24 | ERROR]: No connection to Patrik server
[12.31.2023 12:08:34 | ERROR]: No connection to Patrik server
[12.31.2023 12:08:44 | ERROR]: No connection to Patrik server
[12.31.2023 12:08:54 | ERROR]: No connection to Patrik server
[12.31.2023 12:09:04 | ERROR]: No connection to Patrik server
[12.31.2023 12:09:14 | ERROR]: No connection to Patrik server
[12.31.2023 12:09:24 | ERROR]: No connection to Patrik server
[12.31.2023 12:09:34 | ERROR]: No connection to Patrik server
[12.31.2023 12:09:44 | ERROR]: No connection to Patrik server
[12.31.2023 12:09:54 | ERROR]: No connection to Patrik server
[12.31.2023 12:10:04 | ERROR]: No connection to Patrik server
[12.31.2023 12:10:14 | ERROR]: No connection to Patrik server
[12.31.2023 12:10:24 | ERROR]: No connection to Patrik server
[12.31.2023 12:10:34 | ERROR]: No connection to Patrik server
[12.31.2023 12:10:44 | ERROR]: No connection to Patrik server
[12.31.2023 12:10:54 | ERROR]: No connection to Patrik server
[12.31.2023 12:11:04 | ERROR]: No connection to Patrik server
[12.31.2023 12:11:14 | ERROR]: No connection to Patrik server
[12.31.2023 12:11:24 | ERROR]: No connection to Patrik server
[12.31.2023 12:11:34 | ERROR]: No connection to Patrik server
[12.31.2023 12:11:44 | ERROR]: No connection to Patrik server
[12.31.2023 12:11:54 | ERROR]: No connection to Patrik server
[12.31.2023 12:12:04 | ERROR]: No connection to Patrik server
[12.31.2023 12:57:19 | ERROR]: No connection to Patrik server
[12.31.2023 12:57:29 | ERROR]: No connection to Patrik server
[12.31.2023 12:57:39 | ERROR]: No connection to Patrik server
[12.31.2023 12:57:49 | ERROR]: No connection to Patrik server
[12.31.2023 12:57:59 | ERROR]: No connection to Patrik server
[12.31.2023 12:58:09 | ERROR]: No connection to Patrik server
[12.31.2023 12:58:19 | ERROR]: No connection to Patrik server
[12.31.2023 12:58:29 | ERROR]: No connection to Patrik server
[12.31.2023 12:58:39 | ERROR]: No connection to Patrik server
[12.31.2023 12:58:49 | ERROR]: No connection to Patrik server
[12.31.2023 12:58:59 | ERROR]: No connection to Patrik server
[12.31.2023 12:59:09 | ERROR]: No connection to Patrik server
[12.31.2023 12:59:19 | ERROR]: No connection to Patrik server
[12.31.2023 12:59:29 | ERROR]: No connection to Patrik server
[12.31.2023 12:59:39 | ERROR]: No connection to Patrik server
[12.31.2023 12:59:49 | INFO]: Thumb_Up
[12.31.2023 13:00:12 | INFO]: Open_Palm
[12.31.2023 13:00:12 | INFO]: Thumb_Up
[12.31.2023 13:00:12 | INFO]: Open_Palm
[12.31.2023 13:00:16 | INFO]: Thumb_Up
[12.31.2023 13:00:17 | INFO]: Open_Palm
[12.31.2023 13:00:17 | INFO]: Thumb_Up
[12.31.2023 13:00:20 | INFO]: Pointing_Up
[12.31.2023 13:00:24 | INFO]: Thumb_Down
[12.31.2023 13:00:35 | INFO]: Thumb_Up
[12.31.2023 13:00:41 | INFO]: Thumb_Down
[12.31.2023 13:00:49 | INFO]: Thumb_Up
[12.31.2023 13:00:51 | INFO]: Open_Palm
[12.31.2023 13:00:52 | INFO]: Pointing_Up
[12.31.2023 13:00:53 | INFO]: Closed_Fist
[12.31.2023 13:01:13 | INFO]: Open_Palm
[12.31.2023 13:01:24 | INFO]: Thumb_Down
[12.31.2023 13:01:32 | INFO]: Thumb_Up
[12.31.2023 13:36:18 | INFO]: Open_Palm
[12.31.2023 13:36:25 | ERROR]: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<bg_worker() done, defined at /home/ichiro/docker-gestures/mediapipe/main.py:105> exception=ConnectionClosedError(None, None, None)>
Traceback (most recent call last):
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 963, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1033, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1108, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1165, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/streams.py", line 727, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ichiro/docker-gestures/mediapipe/main.py", line 111, in bg_worker
    msg = await ws.recv()
          ^^^^^^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 939, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent
[12.31.2023 13:55:10 | INFO]: Running on http://0.0.0.0:8005 (CTRL + C to quit)
[12.31.2023 13:55:10 | ERROR]: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<bg_worker() done, defined at /home/ichiro/docker-gestures/mediapipe/main.py:106> exception=ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 8002)")>
Traceback (most recent call last):
  File "/home/ichiro/docker-gestures/mediapipe/main.py", line 110, in bg_worker
    async with websockets.connect(STREAM_URL, ping_interval=None) as ws:
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
           ^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8002)
[12.31.2023 13:56:53 | INFO]: Running on http://0.0.0.0:8005 (CTRL + C to quit)
[12.31.2023 13:56:53 | ERROR]: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<bg_worker() done, defined at /home/ichiro/docker-gestures/mediapipe/main.py:106> exception=ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 8002)")>
Traceback (most recent call last):
  File "/home/ichiro/docker-gestures/mediapipe/main.py", line 110, in bg_worker
    async with websockets.connect(STREAM_URL, ping_interval=None) as ws:
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
           ^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8002)
[12.31.2023 13:59:19 | INFO]: Running on http://0.0.0.0:8005 (CTRL + C to quit)
[12.31.2023 13:59:19 | ERROR]: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<bg_worker() done, defined at /home/ichiro/docker-gestures/mediapipe/main.py:106> exception=ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 8002)")>
Traceback (most recent call last):
  File "/home/ichiro/docker-gestures/mediapipe/main.py", line 110, in bg_worker
    async with websockets.connect(STREAM_URL, ping_interval=None) as ws:
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
           ^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8002)
[12.31.2023 14:03:39 | INFO]: Running on http://0.0.0.0:8005 (CTRL + C to quit)
[12.31.2023 14:03:39 | ERROR]: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<bg_worker() done, defined at /home/ichiro/docker-gestures/mediapipe/main.py:106> exception=ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 8002)")>
Traceback (most recent call last):
  File "/home/ichiro/docker-gestures/mediapipe/main.py", line 110, in bg_worker
    async with websockets.connect(STREAM_URL, ping_interval=None) as ws:
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
           ^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8002)
[12.31.2023 14:04:37 | INFO]: Running on http://0.0.0.0:8005 (CTRL + C to quit)
[12.31.2023 14:04:37 | ERROR]: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<bg_worker() done, defined at /home/ichiro/docker-gestures/mediapipe/main.py:106> exception=ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 8002)")>
Traceback (most recent call last):
  File "/home/ichiro/docker-gestures/mediapipe/main.py", line 110, in bg_worker
    async with websockets.connect(STREAM_URL, ping_interval=None) as ws:
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
           ^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ichiro/.local/lib/python3.11/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8002)
[12.31.2023 14:11:05 | INFO]: Open_Palm
[12.31.2023 14:11:07 | INFO]: Thumb_Up
[12.31.2023 14:11:08 | INFO]: Open_Palm
[12.31.2023 14:11:09 | INFO]: Thumb_Up
[12.31.2023 14:11:10 | INFO]: Open_Palm
[12.31.2023 14:11:11 | INFO]: Thumb_Up
[12.31.2023 14:11:14 | ERROR]: No connection to video stream server (ws://localhost:8002/websocket)
[12.31.2023 14:11:24 | ERROR]: No connection to video stream server (ws://localhost:8002/websocket)
[12.31.2023 14:11:34 | ERROR]: No connection to video stream server (ws://localhost:8002/websocket)
[12.31.2023 14:11:44 | ERROR]: No connection to video stream server (ws://localhost:8002/websocket)
[12.31.2023 14:11:54 | ERROR]: No connection to video stream server (ws://localhost:8002/websocket)
